### ISSUE TITLE
inaccuracy

### ISSUE THREAD

**Issue by bbt-t** [kushedow/pycheat#1]
![pycheat_lists_and_dicts](https://github.com/kushedow/pycheat/assets/84267558/f9d18e51-9afd-4a3d-839a-dadc440d7d25)
![pycheat_loops](https://github.com/kushedow/pycheat/assets/84267558/d36a6957-b76f-467c-81c9-bb4b1ccc3652)
![pycheat_strings](https://github.com/kushedow/pycheat/assets/84267558/22453341-b49a-48df-9023-cf5783efb9cc)

**Comment by bbt-t** [comment]
ах если бы не **SVG** прислал бы **PR**  ...

**Comment by kushedow** [comment]
@bbt-t Большое спасибо, про индексы пока не стал исправлять, остальное поправил
